### ISSUE TITLE
Save the command history and use Up/Down keys to navigate

### ISSUE THREAD

**Issue by alex5imon** [KanoComputing/make-snake#54] opened 2015-04-23 11:28 UTC

**Comment by cwilson-github** [comment] 2015-05-22 06:51
The /bin/make-snake file that I modified is a partial fix for this problem. The script works programmatically, but there is an issue when using the read command and the output from colour_echo. The ANSI terminal codes are not formatted correctly for the read command. I have a solution that can fix the problem but it involves not using the colour_echo script. I think my solution is the simplest to implement but it does not fix the root cause which would involve modifying  kano-toolset/kano/colours.py and  kano-toolset/bin/colours-cli.

**Comment by alex5imon** [comment] 2015-05-26 16:48
@cwilson-github thanks  a for your contributing. Not sure what problem are you referring to. I have tasted your PR and works like a charm. Navigating the command history with Up/Down arrow keys works great. 


What's the problem with `colour_echo`?

**Comment by cwilson-github** [comment] 2015-05-26 19:21
I just added my final revision. Its not so much a problem with colour_echo as it is with the read command. It has to do with the escape characters. The read command uses these constants,

#define RL_PROMPT_START_IGNORE  '\001'
#define RL_PROMPT_END_IGNORE    '\002'
, as escape sequence terminators
They can be found in readline.h with the bash source code. With the previous patch I uploaded it appears to work correctly at first, however, if you load a theme I will just use this command as an example, 'python snake -t custom-theme' then try to navigate up then all the way down through the command history, a portion of the prompt will be overwritten. It has to do with the escape sequences not being terminated properly.

**Comment by FMog** [comment] 2015-05-27 11:20
I have tested this new code, everything works perfectly. I used them without even thinking about it, which is the general aim of good code. Doing without even thinking :)

Test = success

**Closed** 2015-06-01 13:48 UTC
Labels: 4 - Done
